// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';
import {config} from '../models';
import {scanner} from '../models';

export function GetAccountStatus():Promise<Record<string, number>>;

export function GetAgents():Promise<Array<engine.AgentInfo>>;

export function GetConfig():Promise<config.AppConfig>;

export function GetVipEmail():Promise<string>;

export function GetWorkspaces():Promise<Array<scanner.WorkspaceInfo>>;

export function ImportAccounts(arg1:string):Promise<string>;

export function RunRotation():Promise<string>;

export function SaveConfig(arg1:config.AppConfig):Promise<string>;

export function SelectFile():Promise<string>;

export function StartAutoRotation(arg1:number):Promise<void>;

export function StopAutoRotation():Promise<void>;

export function SwitchAccount(arg1:string):Promise<string>;

export function SwitchModel(arg1:string):Promise<string>;
