// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccountStatus() {
  return window['go']['main']['App']['GetAccountStatus']();
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetVipEmail() {
  return window['go']['main']['App']['GetVipEmail']();
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function ImportAccounts(arg1) {
  return window['go']['main']['App']['ImportAccounts'](arg1);
}

export function RunRotation() {
  return window['go']['main']['App']['RunRotation']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function StartAutoRotation(arg1) {
  return window['go']['main']['App']['StartAutoRotation'](arg1);
}

export function StopAutoRotation() {
  return window['go']['main']['App']['StopAutoRotation']();
}

export function SwitchAccount(arg1) {
  return window['go']['main']['App']['SwitchAccount'](arg1);
}

export function SwitchModel(arg1) {
  return window['go']['main']['App']['SwitchModel'](arg1);
}
